# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25c03d5b4680a7c2565dd2e65deea78dd364c76d9b197a46cb35184b7add13e40aeead390a9b6ab97bebe0255605bab9356a69ac78ea0659dd3f7cb6bebbdecd

test:
  secret_key_base: fdfdc58be87f283ff497832b2750f33d91be43ded553c14a54d199e04b547606dca833677b0a47b7c5ffcefc193774d2315c72b99f5b525cf480637534378bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
